"""initial migration

Revision ID: 78dd01ebea11
Revises: 
Create Date: 2024-11-16 22:53:01.631210

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '78dd01ebea11'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Dropping indexes if they exist
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_business_business_id') THEN
                DROP INDEX ix_business_business_id;
            END IF;
        END $$;
    """)
    
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_business_business_name') THEN
                DROP INDEX ix_business_business_name;
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_symptom_symptom_code') THEN
                DROP INDEX ix_symptom_symptom_code;
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_symptom_symptom_name') THEN
                DROP INDEX ix_symptom_symptom_name;
            END IF;
        END $$;
    """)

    # Dropping tables if they exist
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'business') THEN
                DROP TABLE business;
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'symptom') THEN
                DROP TABLE symptom;
            END IF;
        END $$;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Re-creating tables if they don't exist
    op.create_table('symptom',
    sa.Column('symptom_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symptom_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('symptom_code', name='symptom_pkey')
    )
    op.create_index('ix_symptom_symptom_name', 'symptom', ['symptom_name'], unique=False)
    op.create_index('ix_symptom_symptom_code', 'symptom', ['symptom_code'], unique=False)

    op.create_table('business',
    sa.Column('business_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('business_id', name='business_pkey')
    )
    op.create_index('ix_business_business_name', 'business', ['business_name'], unique=False)
    op.create_index('ix_business_business_id', 'business', ['business_id'], unique=False)

    # ### end Alembic commands ###
