"""initial migration

Revision ID: d063289a2a88
Revises: 068c64ae602a
Create Date: 2024-11-16 23:26:58.084160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd063289a2a88'
down_revision = '068c64ae602a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
