"""initial migration

Revision ID: 068c64ae602a
Revises: fc4d37977273
Create Date: 2024-11-16 23:06:59.813784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068c64ae602a'
down_revision = 'fc4d37977273'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
