"""initial migration

Revision ID: fc4d37977273
Revises: 78dd01ebea11
Create Date: 2024-11-16 23:03:50.931031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4d37977273'
down_revision = '78dd01ebea11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
