"""create models for database schema

Revision ID: 0c8c43540ad7
Revises: 
Create Date: 2024-11-16 21:24:36.806575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8c43540ad7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_index(op.f('ix_business_business_id'), 'business', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_business_name'), 'business', ['business_name'], unique=True)
    op.create_table('symptom',
    sa.Column('symptom_code', sa.String(), nullable=False),
    sa.Column('symptom_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('symptom_code')
    )
    op.create_index(op.f('ix_symptom_symptom_code'), 'symptom', ['symptom_code'], unique=False)
    op.create_index(op.f('ix_symptom_symptom_name'), 'symptom', ['symptom_name'], unique=True)
    op.create_table('diagnostics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('symptom_code', sa.String(), nullable=True),
    sa.Column('diagnostic_value', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.business_id'], ),
    sa.ForeignKeyConstraint(['symptom_code'], ['symptom.symptom_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostics_id'), 'diagnostics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnostics_id'), table_name='diagnostics')
    op.drop_table('diagnostics')
    op.drop_index(op.f('ix_symptom_symptom_name'), table_name='symptom')
    op.drop_index(op.f('ix_symptom_symptom_code'), table_name='symptom')
    op.drop_table('symptom')
    op.drop_index(op.f('ix_business_business_name'), table_name='business')
    op.drop_index(op.f('ix_business_business_id'), table_name='business')
    op.drop_table('business')
    # ### end Alembic commands ###
